# Generated by Django 3.2.18 on 2023-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('MISC', 'Misc')], default='MISC', max_length=10),
        ),
    ]
